### ISSUE TITLE
Published to public repo?

### ISSUE THREAD

**Issue by itzg** [bkiers/rrd-antlr4#1]
Do you have your binaries published to a public repo, such as bintray? I would like to share this tool with others in the team, but would rather they use your build rather than mine.

**Comment by WolfgangFahl** [comment]
TreeViewer has moved and the dependency to rrd-antrl4 breaks my code now. Would you please create a new release on maven central?

**Comment by bkiers** [comment]
You mean this one: https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22rrd-antlr4%22 ?

I didn't put it in Maven Central.
