### ISSUE TITLE
enhancement - add pdf function to the code

### ISSUE THREAD

**Issue by cbweixin** [bkiers/rrd-antlr4#4]
I really like this project, it makes reading grammar a lot more easier and instructive. But I have an additional need - I need to print the grammar as a pdf file so I can put it to my mobile device. currently the ultimate output is html page, which is not very portable.

so I added the print pdf feature into the code. please have a look at the screenshot.
![pdf](https://cloud.githubusercontent.com/assets/1326906/10083995/dca4986e-62b5-11e5-86d8-96150043d773.png)

I will initialize a 'Pull requests' for my change, please kindly have a look and give some feedback.

**Comment by bkiers** [comment]
Merged in https://github.com/bkiers/rrd-antlr4/pull/5
