### ISSUE TITLE
Is this project going to be maintained in a public maven repo?

### ISSUE THREAD

**Issue by jshook** [bkiers/rrd-antlr4#8]
I would like to use this in a project, but not unless it is available in a Maven repository.

**Comment by jshook** [comment]
I'm looking at the derivative project for the same reasons. If this project becomes active, I'll look again.

**Comment by bkiers** [comment]
I'm not going to put it in Maven central. But I'm more than happy to give you access to this repo so that you can set it up yourself 😃

**Comment by tianhao960** [comment]
it seems that this project does not publish in maven central. is there a plan? I would like to work on this.thanks.

**Comment by bkiers** [comment]
No, no plan @tianhao960
